### PR TITLE
 Adding Delfin Kalpeni Test Report

### PR DESCRIPTION
**Pull request by NajmudheenCT**
**What type of PR is this?**

> /kind documentation

**What this PR does / why we need it**:
 Adding Delfin Kalpeni Test Report
**Which issue(s) this PR fixes**:

Fixes # NA

**Test Report Added?**:

> /kind NOT-TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by anvithks — APPROVED** [review]
LGTM

**Comment by NajmudheenCT** [comment]
@skdwriting Please merge

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
