### PR TITLE
Add Jerba multi-cloud test reports

### PR DESCRIPTION
**Pull request by rajat-soda**
**What type of PR is this?**
Add Jerba multi-cloud test reports

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
kind documentation

**What this PR does / why we need it**:
Add Jerba multi-cloud test reports
**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
kind TESTED

**Test Report**:

Attached
**Special notes for your reviewer**:

### CODE REVIEW

**Review by NajmudheenCT — APPROVED** [review]
LGTM

**Comment by rajat-soda** [comment]
@PravinRanjan10 @kumarashit @anvithks Pls review and merge

**Review by anvithks — APPROVED** [review]
LGTM

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
