### PR TITLE
add testcases to QA repo

### PR DESCRIPTION
**Pull request by rajat-soda**
**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by rajat-soda** [comment]
This is how the  testcases table looks like.

image

**Comment by rajat-soda** [comment]
@kumarashit @skdwriting Please review

**Comment by kumarashit** [comment]
Looks good.
Couple of questions:
a) 1st column second row is empty?
b) How can user generate this file? Using MD editor ?

**Comment by rajat-soda** [comment]
> Looks good.
> Couple of questions:
> a) 1st column second row is empty?
> b) How can user generate this file? Using MD editor ?

a ) Yes , the  1st col, 2nd row is empty in the original sheet as well.

**Comment by skdwriting** [comment]
What is 'valid inputs'?
Format is ok, if it can be readable in md

**Comment by skdwriting** [comment]
It will be hard to update and scale. Please consider before adding all test cases

**Comment by rajat-soda** [comment]
Closing this branch , as changes made in qa-tests-2 branch.

**Pull request closed without merging**
