### PR TITLE
Add Delfin testcases as csv

### PR DESCRIPTION
**Pull request by joseph-v**
**What type of PR is this?**

> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
>
> /kind new feature
> /kind bug fix
> /kind cleanup
> /kind revert change
> /kind design
> /kind documentation
> /kind enhancement

**What this PR does / why we need it**:
Add Delfin testcases as csv'

**Which issue(s) this PR fixes**:

Fixes #

**Test Report Added?**:
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespace from that line:
> /kind TESTED
> /kind NOT-TESTED

**Test Report**:

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by skdwriting** [comment]
There are many unwanted columns, very hard to traverse, people name is there as last modified etc. Can we clean it up?
Also, are you able to edit on browser easily? (multiple columns and managing commas may be hard ?)

**Comment by joseph-v** [comment]
> There are many unwanted columns, very hard to traverse, people name is there as last modified etc. Can we clean it up?
> Also, are you able to edit on browser easily? (multiple columns and managing commas may be hard ?)

Updated the content after cleanup

**Review by kumarashit — APPROVED** [review]
LGTM

**Review by skdwriting — APPROVED** [review]
LGTM

**Pull request merged**
